services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_pg_data:/var/lib/postgresql"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

  ingest:
    build: .
    depends_on:
      - pgdatabase
    environment:
      DATABASE_URL: "postgresql://root:root@pgdatabase:5432/ny_taxi"
    profiles:
      - manual

volumes:
  ny_taxi_pg_data:
  pgadmin_data:
