[project]
name = "homerwork1"
version = "1.0.0"
description = "Module 1 Homework"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "click>=8.3.1",
  "pandas>=3.0.0",
  "psycopg2-binary>=2.9.11",
  "pyarrow>=23.0.0",
  "sqlalchemy>=2.0.46",
]
